version: '3.8'
networks:
  elastic-network:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=ashish
      - ELASTIC_USERNAME=elastic
      - xpack.monitoring.collection.enabled=true
      - network.host=0.0.0.0
      - http.port=9200
      - ES_JAVA_OPTS=-Xms4g -Xmx4g  # Set JVM heap size to 4GB
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic-network
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=new_kibana_user
      - ELASTICSEARCH_PASSWORD=ashish
      - xpack.monitoring.ui.enabled=true
      - NODE_OPTIONS=--max-old-space-size=2048  # Set JVM heap size to 2GB for Kibana
    depends_on:
      - elasticsearch
    networks:
      - elastic-network
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.1
    container_name: logstash
    environment:
      - xpack.monitoring.enabled=true
      - ELASTIC_USERNAME=new_kibana_user
      - ELASTIC_PASSWORD=ashish
      - xpack.monitoring.collection.enabled=true
      - LS_JAVA_OPTS=-Xms2g -Xmx2g  # Set JVM heap size to 2GB for Logstash
    volumes:
     - ./logstash/pipeline:/usr/share/logstash/pipeline  # Mount your pipeline directory
     - ./logstash/config:/usr/share/logstash/config  
    depends_on:
      - elasticsearch
    networks:
      - elastic-network
    ports:
      - "5044:5044"
      - "9600:9600"

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
  logstash-data:
    driver: local
  ollama:
    driver: local

